### PR TITLE
V2.0.alpha

### PR DESCRIPTION
**Pull request by gthmb**
Heya, I was using your component in a pure Polymer 2.0 (not hybrid) element, and was getting an error calling the legacy Polymer() function. I forked your repo and did the minimal amount of surgery to convert your element to a Polymer 2.0 element. If you like the changes, maybe you can make a new branch/release with these changes for a pure 2.0 element.

Cheers, and thanks for a useful element!

### CODE REVIEW

**Comment by mlisook** [comment]
Thank you for this PR!

I will finish reviewing it today and plan to make it a new release at 2.0.0 as you suggested.

**Comment by mlisook** [comment]
The PR is a go.  I'm going to merge it momentarily.

Can you tell me a little more about the problem that happened calling the legacy Polymer() function, just in case there's a way to fix or document it for users of the hybrid version.

**Comment by gthmb** [comment]
Sure. The hybrid element worked without any issue in my local development environment, and even on the WebComponents.org preview page. However, once I published the component, my component landing page (with some inline demos) where throwing some exceptions around not being able to call the Polymer() method. It might be a red herring, but converting to a Polymer 2.0 element resolved the issue.

To see the exceptions, you can check out the my 0.0.13 tag:
https://www.webcomponents.org/element/gthmb/scatter-image/v0.0.13

To see it running with the 2.0 resize aware, check out the current version:
https://www.webcomponents.org/element/gthmb/scatter-image

The 3rd inline demo is utilizing the resize-aware.

Cheers,
Jon

**Comment by mlisook** [comment]
Love your `scatter-image`, what a cool effect.

Offhand, my impression of the error is that `resize-aware` 1.9.1 is missing `<link rel="import" href="../polymer/polymer.html">`.  I'll do some experiments to verify and release a 1.9.2 version if that's it.

Thanks again.

**Pull request merged**
