### PR TITLE
Used polymer modulizer to convert the element to Polymer 3

### PR DESCRIPTION
**Pull request by DrNiels**
I converted the element to Polymer 3, using the polymer modulizer. Fortunately, it went through without any problems. 

This PR includes #7 as I used the modulizer on my fork.

You would need to change the name of the npm package to use it.

### CODE REVIEW

**Comment by mlisook** [comment]
Thank you for this PR!

I expect to complete testing, merging and publishing this on 6/2.

**Comment by mlisook** [comment]
Looking good, though the demo is not running ...

**Comment by DrNiels** [comment]
Some import paths were broken while modulizing, I guess this applies to the scripts in the demo as well. I will look into it, when I find some time.

**Comment by mlisook** [comment]
I've decided to leave this element at Polymer 2.0 and release [plastic-resize-aware](https://www.webcomponents.org/element/plastic-resize-aware) for Polymer 3.0, which is needed for the next version of plastic-map-info and a work project in progress.

`plastic-resize-aware` uses a `ResizeObserver` in lieu of scroll detection and includes an _element queries_ function  as `plastic-element-query`.

**Comment by DrNiels** [comment]
As you already released your Polymer 3 version quite some time ago, I'll just close here. Thanks for your work!

**Pull request closed without merging**
